version: '3'

services:
  fastapi:
    build: src/fastapi/
    env_file:
      - src/fastapi/.env
    ports: 
      - 8888:8888
    networks:
      - deploy_network
    container_name: fastapi

  streamlit:
    build: src/streamlit/
    env_file:
      - src/streamlit/.env
    depends_on:
      - fastapi
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge
