version: '3'
services:
  fastapi:
    build: src/fastapi/
    ports: 
      - 8888:8888
    networks:
      - deploy_network
    container_name: fastapi

  streamlit:
    build: src/streamlit/
    depends_on:
      - fastapi
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge